### ISSUE TITLE
Username Checker Error

### ISSUE THREAD

**Issue by k1m0ch1** [TIGMINT/TIGMINT#13]
This error is always occur when using the username checker

full log in the attach
[error-log.txt](https://github.com/TIGMINT/TIGMINT/files/5385241/error-log.txt)
![image](https://user-images.githubusercontent.com/5756522/96137682-20997080-0f27-11eb-9df8-fb321be4e794.png)

**Comment by kiranmuddam** [comment]
I will check it. If it is a bug we will fix it.

**Comment by Sumit-sah** [comment]
will check it out , I was busy on some works

**Comment by shanow7** [comment]
http://localhost:3000/username/result

![image](https://user-images.githubusercontent.com/37192410/107862423-180d6400-6e4d-11eb-993b-0a0bb659f87d.png)

Express server listening on port 3000 in development mode
username sony
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/app/Api/../Python_Scripts/result/userpresent.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /app/Api/server.js:174:22
    at PythonShell._endCallback (/app/node_modules/python-shell/index.js:219:20)
    at terminateIfNeeded (/app/node_modules/python-shell/index.js:163:39)
    at ChildProcess.<anonymous> (/app/node_modules/python-shell/index.js:136:13)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/Api/../Python_Scripts/result/userpresent.json'
}

**Comment by kiranmuddam** [comment]
@shanow7  Fixed it,  pull the latest version and try again.
