### ISSUE TITLE
Getting 404 error for Instagram and Username analysis

### ISSUE THREAD

**Issue by dagaltikick** [TIGMINT/TIGMINT#18]
whenever giving search for Instagram and user name analysis I am getting 404 error. Please find the logs below.

└─# node Api/server.js                                                                                 
Express server listening on port 3000 in development mode
username Dagalti
PythonShellError: IndexError: list index out of range
    at PythonShell.parseError (/root/TIGMINT/node_modules/python-shell/index.js:261:21)
    at terminateIfNeeded (/root/TIGMINT/node_modules/python-shell/index.js:144:32)
    at ChildProcess.<anonymous> (/root/TIGMINT/node_modules/python-shell/index.js:136:13)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    ----- Python Traceback -----
    File "/root/TIGMINT/Python_Scripts/instagram/main.py", line 9, in <module>
      dataDir = user_info.Username(username)
    File "/root/TIGMINT/Python_Scripts/instagram/user_info.py", line 14, in Username
      data = required_script.contents[0] {
  traceback: 'Traceback (most recent call last):\n' +
    '  File "/root/TIGMINT/Python_Scripts/instagram/main.py", line 9, in <module>\n' +
    '    dataDir = user_info.Username(username)\n' +
    '  File "/root/TIGMINT/Python_Scripts/instagram/user_info.py", line 14, in Username\n' +
    '    data = required_script.contents[0]\n' +
    'IndexError: list index out of range\n',
  executable: 'python3',
  options: [ '-u' ],
  script: '/root/TIGMINT/Python_Scripts/instagram/main.py',
  args: [ 'Dagalti' ],
  exitCode: 1
}
t4t_tamil
PythonShellError: CRITICAL:root:twint.get:User:'user'
Traceback (most recent call last):
  File "/root/TIGMINT/Python_Scripts/twitter/top_mentions_hashtags/top_mentions_hashtags.py", line 79, in <module>
    main()
  File "/root/TIGMINT/Python_Scripts/twitter/top_mentions_hashtags/top_mentions_hashtags.py", line 76, in main
    get_top_mentions_hashtags(inputUsername)
  File "/root/TIGMINT/Python_Scripts/twitter/top_mentions_hashtags/top_mentions_hashtags.py", line 24, in get_top_mentions_hashtags
    twint.run.Search(c)
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 410, in Search
    run(config, callback)
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 235, in main
    await task
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 253, in run
    raise ValueError("Cannot find twitter account with name = " + self.config.Username)
ValueError: Cannot find twitter account with name = t4t_tamil

    at PythonShell.parseError (/root/TIGMINT/node_modules/python-shell/index.js:269:21)
    at terminateIfNeeded (/root/TIGMINT/node_modules/python-shell/index.js:144:32)
    at ChildProcess.<anonymous> (/root/TIGMINT/node_modules/python-shell/index.js:136:13)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  executable: 'python3',
  options: [ '-u' ],
  script: '/root/TIGMINT/Python_Scripts/twitter/top_mentions_hashtags/top_mentions_hashtags.py',
  args: [ 't4t_tamil' ],
  exitCode: 1
}
tamil
username tamil
PythonShellError: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /user/tamil (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
    at PythonShell.parseError (/root/TIGMINT/node_modules/python-shell/index.js:261:21)
    at terminateIfNeeded (/root/TIGMINT/node_modules/python-shell/index.js:144:32)
    at ChildProcess.<anonymous> (/root/TIGMINT/node_modules/python-shell/index.js:136:13)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    ----- Python Traceback -----
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
      conn = connection.create_connection(
    File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
      for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
    File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  socket.gaierror: [Errno -3] Temporary failure in name resolution
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
      httplib_response = self._make_request(
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
      self._validate_conn(conn)
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
      conn.connect()
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
      conn = self._new_conn()
    File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
      raise NewConnectionError(
  urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
      resp = conn.urlopen(
    File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
      retries = retries.increment(
    File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
      raise MaxRetryError(_pool, url, error or ResponseError(cause))
  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /user/tamil (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/root/TIGMINT/Python_Scripts/username_check/check.py", line 7, in <module>
      account = checker.check(username)
    File "/root/TIGMINT/Python_Scripts/username_check/checker.py", line 107, in check
      youtube(username)
    File "/root/TIGMINT/Python_Scripts/username_check/checker.py", line 82, in youtube
      response = requests.get(url)
    File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
      return request('get', url, params=params, **kwargs)
    File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
      return session.request(method=method, url=url, **kwargs)
    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
      resp = self.send(prep, **send_kwargs)
    File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
      r = adapter.send(request, **kwargs)
    File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
      raise ConnectionError(e, request=request) {
  traceback: 'Traceback (most recent call last):\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn\n' +
    '    conn = connection.create_connection(\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection\n' +
    '    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n' +
    '  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo\n' +
    '    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n' +
    'socket.gaierror: [Errno -3] Temporary failure in name resolution\n' +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen\n' +
    '    httplib_response = self._make_request(\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request\n' +
    '    self._validate_conn(conn)\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn\n' +
    '    conn.connect()\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect\n' +
    '    conn = self._new_conn()\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn\n' +
    '    raise NewConnectionError(\n' +
    'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n' +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send\n' +
    '    resp = conn.urlopen(\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen\n' +
    '    retries = retries.increment(\n' +
    '  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment\n' +
    '    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n' +
    "urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /user/tamil (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n" +                                                                                                  
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/root/TIGMINT/Python_Scripts/username_check/check.py", line 7, in <module>\n' +
    '    account = checker.check(username)\n' +
    '  File "/root/TIGMINT/Python_Scripts/username_check/checker.py", line 107, in check\n' +
    '    youtube(username)\n' +
    '  File "/root/TIGMINT/Python_Scripts/username_check/checker.py", line 82, in youtube\n' +
    '    response = requests.get(url)\n' +
    '  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get\n' +
    "    return request('get', url, params=params, **kwargs)\n" +
    '  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request\n' +
    '    return session.request(method=method, url=url, **kwargs)\n' +
    '  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request\n' +
    '    resp = self.send(prep, **send_kwargs)\n' +
    '  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send\n' +
    '    r = adapter.send(request, **kwargs)\n' +
    '  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send\n' +
    '    raise ConnectionError(e, request=request)\n' +
    "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /user/tamil (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc0933ae50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n",                                                                                                
  executable: 'python3',
  options: [ '-u' ],
  script: '/root/TIGMINT/Python_Scripts/username_check/check.py',
  args: [ 'tamil' ],
  exitCode: 1
}

**Comment by kiranmuddam** [comment]
Instagram authwall is blocking module requests on unrecognised or unknown IP addresses. The issue will be fixed in the next release. @dagaltikick
